version: '3.1'

services:
    jenkins:
        container_name: jenkins
        ports:
            - '8090:8080'
            - '50000:50000'
        image: jenkins/jenkins:lts
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'

