version: '3.1'

services:
    jenkins:
        container_name: jenkins
        ports:
            - '8090:8080'
            - '50000:50000'
        image: jenkins/jenkins:lts
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
